<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="pageTitle" value="Check-in tại địa điểm" scope="request"/>
<%@ include file="/WEB-INF/views/common/header.jsp" %>
<div class="dump-page narrow-page" id="main-content"><div class="dump-card checkin-card"><a href="${pageContext.request.contextPath}/places" class="text-decoration-none">← Quay lại địa điểm</a><div class="checkin-pin">📍</div><h1>Ghi nhận ghé thăm tại địa điểm</h1><h2><c:out value="${place.name}"/></h2><p class="text-muted"><c:out value="${place.address}"/></p><c:if test="${not empty requestScope.errorMessage}"><div class="alert alert-warning"><c:out value="${requestScope.errorMessage}"/></div></c:if>
<c:choose><c:when test="${empty place.latitude or empty place.longitude}"><p>Địa điểm này chưa có tọa độ GPS nên hiện chưa thể Ghi nhận ghé thăm.</p></c:when><c:otherwise><p>Cho phép trình duyệt truy cập vị trí. LocalTrip chỉ lưu tọa độ Ghi nhận ghé thăm để xác minh việc ghé thăm; hệ thống không theo dõi vị trí liên tục.</p><form id="checkinForm" method="post" enctype="multipart/form-data" action="${pageContext.request.contextPath}/checkin"><input type="hidden" name="csrfToken" value="${sessionScope.travelCsrf}"><input type="hidden" name="placeId" value="${place.id}"><input type="hidden" name="latitude" id="latitude"><input type="hidden" name="longitude" id="longitude"><div class="mb-3 text-start"><label class="form-label" for="checkinTrip">Chuyến đi liên quan (không bắt buộc)</label><select class="form-select" id="checkinTrip" name="tripId"><option value="">Không gắn chuyến đi</option><c:forEach items="${trips}" var="trip"><option value="${trip.tripId}" ${selectedTripId eq trip.tripId?'selected':''}><c:out value="${trip.tripName}"/></option></c:forEach></select></div><div class="mb-3"><label class="form-label" for="checkinPhoto">Ảnh kỷ niệm (không bắt buộc, tối đa 5 MB)</label><input class="form-control" type="file" id="checkinPhoto" name="photo" accept="image/jpeg,image/png,image/webp"><small class="text-muted">Ảnh được lưu riêng tư trong Travel Hộ chiếu du lịch; ảnh giúp tiến độ huy hiệu lưu giữ kỷ niệm.</small></div><div class="mb-3"><label class="form-label" for="checkinNote">Ghi chú (không bắt buộc)</label><textarea class="form-control" id="checkinNote" name="note" maxlength="500" rows="3" placeholder="Bạn cảm thấy thế nào khi đến đây?"></textarea></div><div class="form-check text-start mb-3"><input class="form-check-input" type="checkbox" id="shareToDump" name="shareToDump"><label class="form-check-label" for="shareToDump">Chia sẻ Ghi nhận ghé thăm này lên Nhật ký</label></div><div class="mb-3 text-start"><label class="form-label" for="dumpVisibility">Ai có thể xem bài Nhật ký?</label><select class="form-select" id="dumpVisibility" name="dumpVisibility"><option value="FRIENDS">👥 Chỉ bạn bè</option><option value="PUBLIC">🌎 Công khai</option></select><small class="text-muted">Nếu không chọn chia sẻ, Ghi nhận ghé thăm và ảnh vẫn chỉ nằm trong hộ chiếu của bạn.</small></div><button class="btn btn-brand btn-lg w-100" id="checkinButton" type="button" onclick="submitCheckIn()">📍 Xác nhận vị trí và Ghi nhận ghé thăm</button><p id="gpsStatus" class="small text-muted mt-3 mb-0" role="status"></p></form></c:otherwise></c:choose></div></div>
<script>
function submitCheckIn(){var status=document.getElementById('gpsStatus'),button=document.getElementById('checkinButton');if(!navigator.geolocation){status.textContent='Trình duyệt này không hỗ trợ GPS.';return;}button.disabled=true;status.textContent='Đang lấy vị trí GPS...';navigator.geolocation.getCurrentPosition(function(pos){document.getElementById('latitude').value=pos.coords.latitude;document.getElementById('longitude').value=pos.coords.longitude;status.textContent='Đã nhận tọa độ. Đang gửi yêu cầu check-in...';document.getElementById('checkinForm').submit();},function(err){button.disabled=false;status.textContent=err.code===1?'Bạn chưa cấp quyền vị trí. Hãy bật quyền Location cho trình duyệt rồi thử lại.':'Không lấy được vị trí GPS. Hãy thử ở nơi có tín hiệu tốt hơn.';},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
</script>
<%@ include file="/WEB-INF/views/common/footer.jsp" %>
