<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="Bạn bè - Dump" scope="request"/>
<%@ include file="/WEB-INF/views/common/header.jsp" %>
<div class="dump-page" id="main-content"><div class="dump-hero"><div><p class="eyebrow">LOCALTRIP COMMUNITY</p><h1>Kết nối <span>bạn bè</span></h1><p>Chỉ những người đã chấp nhận kết bạn mới xem được bài Nhật ký ở chế độ Bạn bè.</p></div><a class="btn btn-light" href="${pageContext.request.contextPath}/dump">← Quay lại Nhật ký</a></div>
<c:if test="${not empty sessionScope.errorMessage}"><div class="alert alert-danger"><c:out value="${sessionScope.errorMessage}"/></div><c:remove var="errorMessage" scope="session"/></c:if><c:if test="${not empty sessionScope.successMessage}"><div class="alert alert-success"><c:out value="${sessionScope.successMessage}"/></div><c:remove var="successMessage" scope="session"/></c:if>
<div class="dump-friends-grid"><section class="dump-card"><h2>🔎 Tìm người dùng</h2><form method="get" action="${pageContext.request.contextPath}/dump/friends" class="d-flex gap-2"><input class="form-control" name="q" minlength="2" value="<c:out value='${keyword}'/>" placeholder="Tên hoặc email (ít nhất 2 ký tự)"><button class="btn btn-brand" type="submit">Tìm</button></form>
<c:if test="${not empty searchResults}"><div class="friend-results"><c:forEach items="${searchResults}" var="person"><div class="friend-row"><div class="dump-avatar"><c:out value="${person.fullName.substring(0,1)}"/></div><div class="friend-person"><strong><c:out value="${person.fullName}"/></strong><small><c:out value="${person.email}"/></small></div><c:choose><c:when test="${person.status eq 'ACCEPTED'}"><span class="badge text-bg-success">Bạn bè</span></c:when><c:when test="${person.status eq 'PENDING' and person.requesterId eq sessionScope.user.userId}"><span class="badge text-bg-secondary">Đã gửi lời mời</span></c:when><c:when test="${person.status eq 'PENDING'}"><span class="badge text-bg-warning">Đang chờ bạn xử lý</span></c:when><c:otherwise><form method="post" action="${pageContext.request.contextPath}/dump/friends"><input type="hidden" name="csrfToken" value="${sessionScope.travelCsrf}"><input type="hidden" name="action" value="send"><input type="hidden" name="targetUserId" value="${person.userId}"><button class="btn btn-sm btn-outline-primary" type="submit">+ Kết bạn</button></form></c:otherwise></c:choose></div></c:forEach></div></c:if></section>
<section class="dump-card"><h2>✉️ Lời mời đang chờ</h2><c:if test="${empty friendRequests}"><p class="text-muted">Bạn chưa có lời mời kết bạn mới.</p></c:if><c:forEach items="${friendRequests}" var="friend"><div class="friend-row"><div class="dump-avatar"><c:out value="${friend.fullName.substring(0,1)}"/></div><div class="friend-person"><strong><c:out value="${friend.fullName}"/></strong><small><c:out value="${friend.email}"/></small></div><form method="post" action="${pageContext.request.contextPath}/dump/friends" class="d-flex gap-1"><input type="hidden" name="csrfToken" value="${sessionScope.travelCsrf}"><input type="hidden" name="friendshipId" value="${friend.friendshipId}"><button class="btn btn-sm btn-success" name="action" value="accept">Chấp nhận</button><button class="btn btn-sm btn-outline-secondary" name="action" value="decline">Từ chối</button></form></div></c:forEach></section></div></div>
<%@ include file="/WEB-INF/views/common/footer.jsp" %>
