<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="Hộ chiếu du lịch" scope="request"/>
<%@ include file="/WEB-INF/views/common/header.jsp" %>
<div class="dump-page" id="main-content"><div class="dump-hero passport-hero"><div><p class="eyebrow">HÀNH TRÌNH KHÁM PHÁ CỦA BẠN</p><h1>Hộ chiếu <span>du lịch</span></h1><p>Mỗi lần Ghi nhận ghé thăm hợp lệ là một dấu mốc trong hành trình khám phá của bạn.</p></div><a class="btn btn-light" href="${pageContext.request.contextPath}/places">Tìm địa điểm để Ghi nhận ghé thăm ↗</a></div>
<c:if test="${not empty sessionScope.errorMessage}"><div class="alert alert-danger"><c:out value="${sessionScope.errorMessage}"/></div><c:remove var="errorMessage" scope="session"/></c:if><c:if test="${not empty sessionScope.successMessage}"><div class="alert alert-success"><c:out value="${sessionScope.successMessage}"/></div><c:remove var="successMessage" scope="session"/></c:if>
<c:if test="${isOwnPassport}"><section class="dump-card passport-privacy"><form method="post" action="${pageContext.request.contextPath}/passport" class="d-flex justify-content-between align-items-center flex-wrap gap-3"><div><strong>🔐 Quyền riêng tư hộ chiếu</strong><p class="text-muted small mb-0">Mặc định chỉ bạn xem được. Khi công khai, người khác có thể mở hộ chiếu qua liên kết.</p></div><input type="hidden" name="csrfToken" value="${sessionScope.travelCsrf}"><div class="d-flex gap-2"><select class="form-select" name="visibility" aria-label="Quyền riêng tư hộ chiếu"><option value="PRIVATE" ${passportVisibility eq 'PRIVATE'?'selected':''}>Chỉ mình tôi</option><option value="PUBLIC" ${passportVisibility eq 'PUBLIC'?'selected':''}>Công khai</option></select><button class="btn btn-brand" type="submit">Lưu</button></div></form></section></c:if>
<div class="passport-stats"><div class="dump-card passport-stat"><span>📍</span><strong>${summary.placeCount}</strong><small>Địa điểm khác nhau</small></div><div class="dump-card passport-stat"><span>🧭</span><strong>${summary.checkInCount}</strong><small>Ghi nhận ghé thăm hợp lệ</small></div><div class="dump-card passport-stat"><span>🏅</span><strong>${summary.badgeCount}</strong><small>Huy hiệu đã đạt</small></div><div class="dump-card passport-stat"><span>📷</span><strong>${summary.photoCount}</strong><small>Ghi nhận ghé thăm có ảnh</small></div></div>
<div class="passport-columns"><section class="dump-card"><div class="section-heading"><div><p class="eyebrow">NHẬT KÝ HÀNH TRÌNH</p><h2>Nhật ký khám phá</h2></div><span class="text-muted small">Mới nhất trước</span></div><c:if test="${empty checkIns}"><div class="dump-empty"><span>🗺️</span><h3>Hộ chiếu của bạn đang chờ dấu mốc đầu tiên</h3><p>Mở trang một địa điểm có tọa độ GPS và nhấn Ghi nhận ghé thăm ngay.</p><a class="btn btn-brand" href="${pageContext.request.contextPath}/places">Khám phá địa điểm</a></div></c:if><div class="passport-timeline"><c:forEach items="${checkIns}" var="item"><div class="passport-entry"><div class="timeline-dot">✓</div><div class="passport-entry-content"><div class="d-flex justify-content-between gap-2 flex-wrap"><h3><c:out value="${item.placeName}"/></h3><small><fmt:formatDate value="${item.checkInTime}" pattern="dd/MM/yyyy HH:mm"/></small></div><p class="text-muted mb-1"><c:out value="${item.categoryName}"/> · <c:out value="${item.address}"/></p><c:if test="${not empty item.note}"><p class="mb-1"><c:out value="${item.note}"/></p></c:if><c:if test="${item.hasPhoto}"><span class="badge text-bg-light">📷 Có ảnh</span><c:if test="${not empty item.imageId}"><c:if test="${isOwnPassport}"><a href="${pageContext.request.contextPath}/checkin/image?id=${item.imageId}" target="_blank" rel="noopener" class="small ms-2">Xem ảnh</a></c:if></c:if></c:if></div></div></c:forEach></div></section>
<section class="dump-card"><div class="section-heading"><div><p class="eyebrow">THÀNH TÍCH KHÁM PHÁ</p><h2>Huy hiệu khám phá</h2></div></div><p class="text-muted small">Huy hiệu được trao tự động sau Ghi nhận ghé thăm hợp lệ. Mỗi địa điểm chỉ được tính một lần cho thành tích địa điểm độc nhất.</p><div class="badge-list"><c:forEach items="${badges}" var="badge"><div class="passport-badge ${badge.earned?'earned':'locked'}"><div class="passport-badge-icon"><c:out value="${badge.icon}"/></div><div class="passport-badge-info"><strong><c:out value="${badge.badgeName}"/></strong><p><c:out value="${badge.description}"/></p><div class="progress" role="progressbar" aria-valuenow="${badge.progress}" aria-valuemin="0" aria-valuemax="${badge.threshold}"><div class="progress-bar" style="width:${badge.progress * 100 / badge.threshold > 100 ? 100 : badge.progress * 100 / badge.threshold}%"></div></div><small><c:choose><c:when test="${badge.earned}">Đã đạt</c:when><c:otherwise>${badge.progress}/${badge.threshold} tiến độ</c:otherwise></c:choose></small></div><c:choose><c:when test="${badge.earned}"><span class="badge text-bg-success">Đã đạt</span></c:when><c:otherwise><span class="badge text-bg-secondary">🔒</span></c:otherwise></c:choose></div></c:forEach></div></section></div></div>
<%@ include file="/WEB-INF/views/common/footer.jsp" %>
