<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="Báo cáo Dump" scope="request"/>
<%@ include file="/WEB-INF/views/common/header.jsp" %>
<div class="container py-4" id="main-content"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-4"><div><p class="eyebrow">ADMIN MODERATION</p><h1 class="h3 mb-1">Báo cáo bài viết Dump</h1><p class="text-muted mb-0">Kiểm tra báo cáo và cập nhật trạng thái xử lý.</p></div><a href="${pageContext.request.contextPath}/admin" class="btn btn-outline-secondary">← Dashboard</a></div>
<c:if test="${not empty sessionScope.errorMessage}"><div class="alert alert-danger"><c:out value="${sessionScope.errorMessage}"/></div><c:remove var="errorMessage" scope="session"/></c:if><c:if test="${not empty sessionScope.successMessage}"><div class="alert alert-success"><c:out value="${sessionScope.successMessage}"/></div><c:remove var="successMessage" scope="session"/></c:if>
<div class="table-responsive bg-white rounded-4 border"><table class="table align-middle mb-0"><thead><tr><th>Thời gian</th><th>Bài viết</th><th>Người đăng</th><th>Người báo cáo</th><th>Lý do</th><th>Trạng thái</th><th>Xử lý</th></tr></thead><tbody><c:forEach items="${reports}" var="r"><tr><td><fmt:formatDate value="${r.createdAt}" pattern="dd/MM/yyyy HH:mm"/></td><td><strong>#${r.postId}</strong><div class="small text-muted"><c:out value="${r.content}"/></div><span class="badge text-bg-light"><c:out value="${r.visibility}"/></span></td><td><c:out value="${r.ownerName}"/></td><td><c:out value="${r.reporterName}"/></td><td><c:out value="${r.reason}"/></td><td><span class="badge ${r.status eq 'OPEN'?'text-bg-warning':r.status eq 'REVIEWED'?'text-bg-success':'text-bg-secondary'}"><c:out value="${r.status}"/></span></td><td><c:if test="${r.status eq 'OPEN'}"><form method="post" class="d-flex gap-1" action="${pageContext.request.contextPath}/admin/dump-reports"><input type="hidden" name="csrfToken" value="${sessionScope.travelCsrf}"><input type="hidden" name="reportId" value="${r.reportId}"><button class="btn btn-sm btn-success" name="status" value="REVIEWED">Đã xem</button><button class="btn btn-sm btn-outline-secondary" name="status" value="DISMISSED">Bỏ qua</button></form></c:if></td></tr></c:forEach><c:if test="${empty reports}"><tr><td colspan="7" class="text-center text-muted py-5">Chưa có báo cáo Dump.</td></tr></c:if></tbody></table></div></div>
<%@ include file="/WEB-INF/views/common/footer.jsp" %>
